apiVersion: v1
kind: Secret
metadata:
  name: {{ include "foreman.fullname" . }}-config
  labels:
    {{- include "foreman.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_HOST: {{ include "foreman.postgresqlHost" . | b64enc | quote }}
  POSTGRES_DATABASE: {{ .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  POSTGRES_USERNAME: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  REDIS_URL: {{ include "foreman.redisUrl" . | b64enc | quote }}
{{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
